require 'sleek/queries/query'
require 'sleek/queries/targetable'
require 'sleek/queries/count'
require 'sleek/queries/count_unique'
require 'sleek/queries/minimum'
require 'sleek/queries/maximum'
require 'sleek/queries/average'
require 'sleek/queries/sum'
